### PR TITLE
Added files in Intro to C++, simple arithmetics and arrays 

### PR DESCRIPTION
**Pull request by ShrutiSolani**

### CODE REVIEW

**Comment by jmrchelani** [comment]
It seems alright but Change the names of the files for example,
Hello World example should be HelloWorld.cpp instead of the folder's name. 
Same for the arrays and arithmetic. Make sure the names are following the conventions and are appropriate.
Fix this and reply so I can merge it.

Thanks for your interest and help.
Cheers!

**Comment by jmrchelani** [comment]
Accepted, Thanks.

**Comment by ShrutiSolani** [comment]
Will add more files in future.

**Comment by jmrchelani** [comment]
Sure, any type of contribution is welcome.
Pull a request once you think you have added anything, I will welcome it surely.

Thanks.

**Pull request merged**
